[package]
name = "libhook"
version = "0.0.1"
edition = "2021"

[dependencies]
libc = "0.2.119"
base-coroutine = { path = "../base-coroutine" }
timer = { path = "../timer" }

[build-dependencies]
cbindgen = "0.24.3"
rustversion = "1.0.6"

[lib]
crate-type = ["cdylib"]
name = "hook"
path = "src/lib.rs"
