[licenses]
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "Unlicense",
  "Unicode-DFS-2016",
  "MIT"
]
confidence-threshold = 0.95
private = {ignore = true}

[bans]
multiple-versions = "allow"
