[package]
name = "open-coroutine-hooks"
version = "0.1.0"
edition = "2021"
authors = ["zhangzicheng@apache.org"]
description = "The syscall hook for open-coroutine"
repository = "https://github.com/acl-dev/open-coroutine/tree/dev/libhook"
keywords = ["open-coroutine", "hook", "syscall"]
categories = ["os", "concurrency", "asynchronous"]
license = "LGPL-3.0 OR Apache-2.0"

[dependencies]
