[package]
name = "base-coroutine"
version = "0.1.0"
edition = "2021"

[dependencies]
corosensei = "0.1.3"
once_cell = "1.13.0"
object-list = { path = "../object-list" }
timer = { path = "../timer" }
id-generator = { path = "../id-generator" }
