[package]
name = "base-coroutine"
version = "0.0.2"
edition = "2021"
authors = ["zhangzicheng@apache.org"]
description = "A fast and safe implementation of stackful coroutines with schedulers."
repository = "https://github.com/acl-dev/open-coroutine/tree/dev/base-coroutine"
license = "LGPL-3.0 OR Apache-2.0"

[dependencies]
libc = "0.2.137"
once_cell = "1.13.0"
scopeguard = "1.1.0"
object-collection = { version = "0.0.2", path = "../object-collection" }
timer-utils = { version = "0.0.2", path = "../timer-utils" }

[target."cfg(windows)".dependencies]
kernel32-sys = "0.2.2"
winapi = "0.3.9"

[build-dependencies]
cc = "1.0.73"
rustversion = "1.0.6"
