name: build open_coroutine_hooks

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  linux:
    name: build open_coroutine_hooks on linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo clean
        run: |
          cd ${{ github.workspace }}
          /home/runner/.cargo/bin/cargo clean
      - name: cargo build --release -p open_coroutine_hooks
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release -p open_coroutine_hooks
      - uses: actions/upload-artifact@v2
        with:
          name: open_coroutine_hooks
          path: target/release/libopen_coroutine_hooks.so
          if-no-files-found: error

  macos:
    name: build open_coroutine_hooks on macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo clean
        run: |
          cd ${{ github.workspace }}
          /Users/runner/.cargo/bin/cargo clean
      - name: cargo build --release -p open_coroutine_hooks
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release -p open_coroutine_hooks
      - uses: actions/upload-artifact@v2
        with:
          name: open_coroutine_hooks
          path: target/release/libopen_coroutine_hooks.dylib
          if-no-files-found: error

#  windows:
#    name: build open_coroutine_hooks on windows
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Install toolchain
#        uses: actions-rs/toolchain@v1
#        with:
#          profile: minimal
#          toolchain: nightly
#          override: true
#      - name: cargo clean
#        run: |
#          cd ${{ github.workspace }}
#          C://Users//runneradmin//.cargo//bin//cargo.exe clean
#      - name: cargo +nightly build --release -p open_coroutine_hooks
#        uses: actions-rs/cargo@v1
#        with:
#          command: build
#          args: --release -p open_coroutine_hooks
#      - uses: actions/upload-artifact@v2
#        with:
#          name: open_coroutine_hooks
#          path: target/release/open_coroutine_hooks.dll
#          if-no-files-found: error
#      - uses: actions/upload-artifact@v2
#        with:
#          name: open_coroutine_hooks
#          path: target/release/open_coroutine_hooks.dll.lib
#          if-no-files-found: error
