name: build libhook

on: [ push,pull_request ]

jobs:
  linux:
    name: build libhook on linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo build --release -p libhook
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release -p libhook
      - uses: actions/upload-artifact@v2
        with:
          name: libhook
          path: target/release/libhook.so
          if-no-files-found: error

  macos:
    name: build libhook on macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo build --release -p libhook
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release -p libhook
      - uses: actions/upload-artifact@v2
        with:
          name: libhook
          path: target/release/libhook.dylib
          if-no-files-found: error

  windows:
    name: build libhook on windows
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: cargo +nightly build --release -p libhook
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release -p libhook
      - uses: actions/upload-artifact@v2
        with:
          name: libhook
          path: target/release/hook.dll
          if-no-files-found: error
      - uses: actions/upload-artifact@v2
        with:
          name: libhook
          path: target/release/hook.dll.lib
          if-no-files-found: error
