name: Code Coverage

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.png'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.png'

env:
  CARGO_TERM_COLOR: always
  CODECOV_TOKEN: 86ae569f-70d3-4c7b-833e-6e8fc97ea9f3
  # If a test crashes, we want to know which one it was.
  RUST_TEST_THREADS: 1
  RUST_BACKTRACE: 1

jobs:
  coverage:
    name: Run cargo coverage on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.81.0
          profile: minimal
          override: true
          components: llvm-tools-preview
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: bash -c "${{ matrix.cargo }} llvm-cov --release --all --lcov --output-path lcov.info"
      - name: Generate code coverage with all features
        run: bash -c "${{ matrix.cargo }} llvm-cov --all-features --release --all --lcov --output-path lcov-all-features.info"
      - name: Upload coverage to Codecov
        run: |
          bash <(curl -s https://codecov.io/bash) -f lcov.info -t ${{ env.CODECOV_TOKEN }} || powershell -Command "iwr -useb https://codecov.io/bash | iex" -f lcov.info -t ${{ env.CODECOV_TOKEN }}
          bash <(curl -s https://codecov.io/bash) -f lcov-all-features.info -t ${{ env.CODECOV_TOKEN }} || powershell -Command "iwr -useb https://codecov.io/bash | iex" -f lcov-all-features.info -t ${{ env.CODECOV_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            cargo: ulimit -Sl 512 && ulimit -Hl 512 && sudo -u runner /home/runner/.cargo/bin/cargo
          - os: macos-14
            cargo: ulimit -Sl 512 && ulimit -Hl 512 && sudo -u runner /Users/runner/.cargo/bin/cargo
          - os: windows-latest
            cargo: C://Users//runneradmin//.cargo//bin//cargo.exe
